### ISSUE TITLE
ECS - Get AppVeyor running again.

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#111]
I think I've got it getting the nuget packages properly now, I think we need to get it to ignore the mac and gtk projects, I've done a little bit of googling on how to get appveyor to unload projects before build but haven't had any success finding the info. maybe we do need a build script?

**Comment by se5a** [comment]
ok so it did work, but then now it's not? I've been trying stuff with the appveyor settings without success. CBF has kicked in for the evening.

**Comment by firefly2442** [comment]
Do you mean the "build failing" in the readme file?  That's just referencing another branch.  Where do you see it failing?

**Comment by se5a** [comment]
huh so it was. still I've updated that. it now says it's passing there. but when I click on it, it takes me to the project in my appveyor where it says its failed. it appears to be ignoring the appveyor.yml

**Comment by firefly2442** [comment]
I wonder if there are some settings that are different between users?

https://ci.appveyor.com/project/ **se5a** /pulsar4x/history

vs.

https://ci.appveyor.com/project/ **intercross21** /pulsar4x/history

**Comment by se5a** [comment]
yeah, can't figure out what though. the yaml is supposed to take precedence unless explicitly set to ignore. I've set it back to link to intercross's since I cant figure it out.

**Comment by se5a** [comment]
Eh this is working now, might as well close it I guess.
