### ISSUE TITLE
ECS: ECS-Comms Branch

### ISSUE THREAD

**Issue by DifferentLevelDan** [Pulsar4xDevs/Pulsar4x#113]
@se5a Where are we with the ECS Comms branch? I fear the branches (ECS-Comms and ECS-Switchover) have split sufficently that we need to choose one and banish the other. Personally, I think the ECS-Comms branch is the underdeveloped and most new work is going into ECS-Switchover.

Can we delete ECS-Comms outright? I doubt a merge is going to be sane to do at this point, is there any work worth saving that you can manually move over? I'd like to get rid of ECS-Comms in the near-future.

**Comment by se5a** [comment]
It may have some code we want to copy over when we start attempting this again.

**Comment by Rod-Serling** [comment]
You're the one with the knowledge on what's in there. If you can, let us know the major features that ECS-Comms has that other braches might not, so if we go to implement something we can check there for possible partial/full implementation

**Comment by DuctTapeMor** [comment]
Speaking of knowledge, is there anyway you can compile a list of goals for the next release? So that I know if its worthwhile creating new issues over the bugs that I encountered. Also hello.

**Comment by se5a** [comment]
not a lot of point right now. at this stage most 'bugs' are stuff that we're aware of, or bits of code that will change/are unimplemented features. once we've got something a bit more stable and 'playable' we'll be looking for bug reports.
