### ISSUE TITLE
ECS: StarSystem JSON Import/Export

### ISSUE THREAD

**Issue by Antagonistic** [Pulsar4xDevs/Pulsar4x#12]
Edit by Rod-Serling:
We have implimented XML output that can be imported into Excel, however, we still need a way for StarSystems to be imported/exported directly into the game from JSON.

These should be PublicAPI functions of the Library.

Original Issue by Antagonistic:
In order to check what changes to stargen does to the quality of planets we generate, I need to do some data analysis.  Generate 1000 starsystems, create some charts and graphs, compare with an earlier version etc... Excell is okay for this, but for that I need to export starsystems.

We need an export anyway on the F9 screen, with several options, json, csv, etc to export the selected system or all systems

I would also like a function in the Tests project to export the aforementioned 1000 starsystems.

Some nice classes are available here:
http://stackoverflow.com/questions/2422212/simple-c-sharp-csv-excel-export-class

**Comment by Rod-Serling** [comment]
ECS-Comms branch is currently capable of outputting SolarSystems to XML as of commit 05a776e.

The XML is formatted to be able to be imported into Excel.

I do agree however, that we should be able to export/import SolarSystems to JSON aswell. I am updating the original issue to specify this.

I don't believe CSV output is required at this point.

**Comment by se5a** [comment]
Can this be closed now Snopy? iirc you implemented this.

**Comment by Rod-Serling** [comment]
Fully implemented in 7cba59aff34acf4a37e6631cc145f6558a949763
