### ISSUE TITLE
Minor refactors.

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#128]
Just a  quick list of minor refactoring and renaming that I don't want to do *right now*. 

rename SystemBodyDB to SystemBodyInfoDB for consistency. 
rename SystemBodyDB.Type to SysBodyType or something other than Type.

**Comment by DuctTapeMor** [comment]
Seems strightforward, If you are looking for someone todo it now, I can probably do it in a few minutes.

**Comment by se5a** [comment]
I'm kind of messing with stuff that uses that in another branch, this is really just a reminder to me to look at it after I've finished. don't want to do it right now to prevent conflicts.

**Comment by se5a** [comment]
if you know any openGL you could mess with the SystemView branch...

**Comment by DuctTapeMor** [comment]
I have some background and everything code wise seem familiar, but I am not a program and have no experience with any of the stuff you guys are using, Sure I can probably learn as I go with help of the might net, but I am more likely to interfere on anything major you guys are working on.

**Comment by se5a** [comment]
well if you know a little bit, then you probably know more than me, I'm trying to refactor two different peoples code who've since left, and I know next to nothing about opengl. if you want to give it a shot, catch me on #pulsar4x on freenode. I'm going out soon though so likely will be afk for a few hours.

**Comment by nskillen** [comment]
Heads up, opened PR #129 to get the OpenGL to actually resize properly.

**Comment by Rod-Serling** [comment]
@DuctTapeMor We generally coordinate and talk via IRC on freenode. Channel #Pulsar4x
Join us there and we can get you something to work on without interfering with the rest of us if you're worried, or just to chat, ask questions, or anything. Many of us idle there 24/7 so pop in and say hi.
