### ISSUE TITLE
Crashes during loading

### ISSUE THREAD

**Issue by Josephine98** [Pulsar4xDevs/Pulsar4x#130]
When loading a save with the version that Rod-Sterling compiled, it gives out this crash:

Exception thrown while Loading Game:

Pulsar4X.ECSLib.GuidNotFoundException
Exception of type 'Pulsar4X.ECSLib.GuidNotFoundException' was
thrown.

Thrown in function:
Pulsar4X.ViewModel.SystemVM Create(Pulsar4X.ViewModel.GameVM,
SystemGuid)

Stack Trace:

at PuIsar4X.ViewMode|.SystemVM.Create(GameVM gameVM, Guid
starSystemGuid) in
D:\GitHub\PuIsar4x\Pulsar4X\ViewMode|Lib\ViewMode|s\SystemVM.cs:
line 169

at PuIsar4X.ViewMode|.GameVM.set_CurrentFaction(Entity value) in
D:\GitHub\Pu|sar4x\Pulsar4X\ViewModelLib\ViewMode|s\GameVM.cs:li
ne 40

at Pulsar4X.ViewMode|.GameVM.LoadGame(String pathToFile) in
D:\GitHub\Pu|sar4x\Pulsar4X\ViewModelLib\ViewMode|s\GameVM.cs:li
ne 152

at
Pulsar4X.CrossPlatformUI.Cornmands.LoadGame.OnExecuted(EventArg
s e) in
D:\GitHub\Pulsar4x\PuIsar4X\PuIsar4X.CrossPlatformURCommands\Lo
adGame.cs:line44

**Comment by Rod-Serling** [comment]
This is due to the UI assuming no Spacemaster password, and not validating authorization requests returned from the ECSLib. We need to implement a player selection screen that establishes and authToken upon game loading and player changes.

**Comment by DifferentLevelDan** [comment]
Currently on ECS-SystemView branch, there are multiple crashes while attempting to load the game. I've not had the time to track down all of the issues, but it seems to stem from updating the views and the system viewmodels. We need a more in-depth analysis of the current points of failure on loading the game so we can start to work on resolving them.

**Comment by behindcurtain3** [comment]
Enough has changed I don't think this is a valid issue anymore.
