### ISSUE TITLE
Generate ComponentTemplates for Release 1

### ISSUE THREAD

**Issue by DifferentLevelDan** [Pulsar4xDevs/Pulsar4x#139]
We need ComponentTemplates designed and implemented for the following facilities:

Construction factories
Mines
Refineries 

These need to be added to the default Json files utilizing the new IndustryAbilityDB in the ECS-Processors branch. 

@se5a is the ComponentTemplates lead if you have any questions.
@Rod-Serling is the ECS-Processors and IndustryAbilityDB lead if you have questions.

**Comment by DifferentLevelDan** [comment]
This is causing a crash on ECS-Processors branch due to invalid Json format for current components.

**Comment by se5a** [comment]
Mines are done and, (in the ECS-Cargo branch) work all the way up to the ui showing raw minerals in the colony cargo control.

**Comment by agm-114** [comment]
Done.
