### ISSUE TITLE
Save games cannot be saved outside of the game's directory.

### ISSUE THREAD

**Issue by DifferentLevelDan** [Pulsar4xDevs/Pulsar4x#142]
When attempting to save the game, the save file will be placed in the save folder as the .exe regardless of actual location passed. This is likely due to the attempts at cross-platform finding the current directory of the .exe for other reasons.

See:
@Rod-Serling for questions related to the SerializationManager

**Comment by se5a** [comment]
moved this to release 2. 
honestly, we're not going to  need this feature for a long long while yet, but we can get all save load fixes done with a full test suite in release 2.

**Comment by EnigmaticCrypt** [comment]
If its ok. I want to take this up as the starting point to know about the project more.

**Comment by se5a** [comment]
sure. were you ociule on IRC?

**Comment by EnigmaticCrypt** [comment]
ociule ? No i dont have IRC setting. I just downloaded it and going through code.

**Comment by se5a** [comment]
Ah, there was someone asking questions on irc around about the same time you posted in here. Coincidence I guess. If you do have questions it's probably easiest to catch me on irc channel #pulsar4x on freenode.

**Comment by se5a** [comment]
Also, you'll want to be looking at the ecs-crossplatform branch, as that one is most up to date.

**Comment by agm-114** [comment]
Opening new issue.
