### ISSUE TITLE
System map Camera. 

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#144]
Zoom, Pan, etc. 
There's camera object here: https://github.com/Pulsar4xDevs/Pulsar4x/tree/ECS-CrossPlatform/Pulsar4X/Pulsar4X.CrossPlatformUI/Lib

needs to be implemnted... here? https://github.com/Pulsar4xDevs/Pulsar4x/blob/ECS-CrossPlatform/Pulsar4X/Pulsar4X.CrossPlatformUI/Views/SystemMap_DrawableView.xeto.cs#L186
I think...

matrix transforms are a bit over the top of my  head.

**Comment by se5a** [comment]
@NathanH- started on this and made some progress. Nathan, you gave me gists for most the stuff you did, but not all the changes to Camera2d, looking at the gists, you've created two new methods in Camera2d, but you didn't include those in the gists. 

@SnopyDogy where've you disappeared too? I need some advise on a few features.

**Comment by NathanH-** [comment]
Do we need anything else with regards to the camera except UI stuff?

**Comment by se5a** [comment]
Tilt and rotate.

I'm joking. I think we're good with the camera now. I guess we can close this.
