### ISSUE TITLE
Complete GTK# GUI

### ISSUE THREAD

**Issue by PsiDog** [Pulsar4xDevs/Pulsar4x#15]
An incomplete GTK# GUI has been written as a WinForm alternative for Macs and Linux. 
It still needs a lot of work to catch up. Mark this as complete whenever the GTK GUI catches up to the WinForm GUI.

Subissues included:
- Finish filling in the General System Display data
- Implementing Databinding, if possible
- Rendering the System Map

**Comment by Rod-Serling** [comment]
GTK# GUI has been inactive for two years, and deleted as abandoned and non-functional. Initial milestones will continue to use the Pulsar.UI winforms UI until time can be devoted to a better general GUI.
