### ISSUE TITLE
Orbit Ring positions

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#152]
OrbitRings in the NewOrbitRings branch are out of position.

these orbit rings should be
a bit faster than how they're currently done.
a bit more control over the number of alpha arcs (OrbitRing.Segments = 1 to 255)
a bit more control over how much of the ring gets shown (OrbitRing.OrbitPercent )
will look better with lower segment counts (due to being arcs rather than lines)

In the NewOrbitRings branch, they are the red arcs, the white being the currently drawn ones.

ellipses are drawn by defining a rectangle, giving a position, and a width and a height.
arcs are drawn exactly the same way as an ellipse, but are given a start and sweep angle.

to get an ellipse, we set the width and height, which gives us an ellipse, you can see this in the contructor. this is static. 
we then have to rotate the ellipse so that the major axis is in line with the orbit we're trying to represent, this is also static, set in the constructor, and is is done as a transform in DrawMe().

the other important point is we have to position and rotate around the focal point, the focal point is static, but the position is not. these are also set in the contructor, and done as transforms in the DrawMe() method.
note that the position is stored as a reference to the datablob. 

I _think_ the rotation is correct (for an non inclined orbit anyway, for an inclined orbit the current calculation is definitely wrong. I'm not sure how to calculate for an inclined orbit, but at this point all orbits are 2d)
I suspect the focal point may be off. as I understand it, in a two body orbit, the child's focal point is at the parent's position.  (is this correct? maybe this is wrong)

class is here: https://github.com/Pulsar4xDevs/Pulsar4x/blob/ECS-NewOrbitRing/Pulsar4X/Pulsar4X.CrossPlatformUI/Views/OrbitRing.cs

**Comment by se5a** [comment]
Maybe you want to take a stab at this @NathanH- ? I'm going to be away for this weekend, and probably next so won't be around to answer questions if you start digging at other stuff...  up to you.

**Comment by NathanH-** [comment]
I'm not sure what you're trying to do, so I'm going to have to wait until you get back. As far as inclined orbits are concerned, I'm not sure what if anything that gets us, but that seems like it would just be some sort of matrix multiplication.

**Comment by tsonnier** [comment]
I'm not terribly familiar with orbital mechanics, but my guess is that
inclined orbits would only have any effect in a three dimensional
simulation.

On Sat, May 21, 2016 at 11:13 PM, Nathan Hittinger <notifications@github.com

**Comment by se5a** [comment]
Yeah,  currently orbits are only created non inclined, thr only reason to fix that bit now is so it doesn't create a problem later on and we've forgoten or moved on.

**Comment by se5a** [comment]
What im trying to do is place the red coloured ellipses where the white coloured ones are.

**Comment by NathanH-** [comment]
well I dug up the old code I did for orbits a while back, it may help. something is definitely wrong with the way you're doing it, Mars and Mercury both seem to have the opposite requirement for the right corrective transformation.

**Comment by se5a** [comment]
I was under the impression that the rings in master were done the same/similar to how the white rings are done.  ie, straight line segments from positions the planet would be at time intervals.

**Comment by se5a** [comment]
So we seem to have fixed the primary problem with this, (well done Nathan) though the fix leads me to suspect that there is a bug in the orbitProcessor somewhere, since the 'fix' doesn't make a whole lot of sense, ie: 
_rotation = (float)(_orbitDB.LongitudeOfAscendingNode + _orbitDB.ArgumentOfPeriapsis*2); 
we can put trying to figure that out on the backburner, but it should probably be looked into at some point, just for the sake of correctness. 

Now that the orbit line is in the right place, I can see the start of the orbit line is not always where the planet is, at first I thought that this was because I wasn't adjusting for the planet speeding up and slowing down on elliptical orbits, but looking at the code, I'm getting the angle for where the start of the line should be directly from the position of the planet. so that's not it. though it does appear to be more prominent on more elliptical orbits... odd.  
Do you want to keep banging away at this Nathan or do you want to do something different now?

**Comment by se5a** [comment]
@NathanH- I understand why the StartArcAngle is wrong now.
It's the angle from the orbits _focal point_ to the planet. but an arcs start angle is from the center of the ellipse.
StartArcAngle needs to be calculated from the center of the orbit ellipse, ie we need to do Atan2 on the planet position minus the focal offset or something. 
that's likely to be way easier than trying to figure out the angle difference afterwards.

**Comment by se5a** [comment]
something like this I think should be the right way to do it:

``` csharp
private float GetStartArcAngle()
{
    //since teh _focalPoint is only an X component we dont' bother calculating the Y part of the matrix
    double focalX = (_focalPoint * Math.Cos(_rotation * Math.PI / 180)); // - 0 * sin(rotation) 
    double focalY = (_focalPoint * Math.Sin(_rotation * Math.PI / 180)); // + 0 * cos(rotation)
    Vector4 focalPoint = new Vector4(focalX, focalY, 0, 0);
    focalPoint -= _bodyPositionDB.RelativePosition;

    float rotation = (float)(Math.Atan2(focalPoint.Y, focalPoint.X) * 180 / Math.PI);

    return rotation;
}
```

**Comment by se5a** [comment]
That doesn't quite work out btw. But I ran out of time to test it further.

**Comment by se5a** [comment]
fixed it in the crossplatform branch.
here's the nifty function:

``` csharp
private float GetStartArcAngle()
{
    //since teh _focalPoint is only an X component we dont' bother calculating the Y part of the matrix
    double focalX = (_focalPoint * Math.Cos(_rotation * Math.PI / 180)); // - 0 * sin(rotation) 
    double focalY = (_focalPoint * Math.Sin(_rotation * Math.PI / 180)); // + 0 * cos(rotation)
    //addt the body posistion
    Vector4 offsetPoint = new Vector4(focalX, focalY, 0, 0) + _bodyPositionDB.RelativePosition;
    //find the angle to the offset point
    float angle = (float)(Math.Atan2(offsetPoint.Y, offsetPoint.X) * 180 / Math.PI);
    //subtract the _rotation, since this angle needs to be ralitive to the elipse, and the elipse gets _rotated
    angle -= _rotation;
    //and finaly, normalise it useing modulo arrithmatic.
    angle = angle % 360;
    if (angle < 0)
        angle += 360;
    return angle;
}
```

**Comment by se5a** [comment]
we have to multiply the Y axis by the eccentricity, because an arc angle on an ellipse is relative to the ellipse:  
https://www.dropbox.com/s/18m2j7pdfbm35a8/Screenshot%202016-08-15%2000.18.56.png?dl=0
both those white arcs start at 45 degrees.

**Comment by se5a** [comment]
Got it:

`````` csharp
private float GetStartArcAngle()
{

    Vector4 pos = _bodyPositionDB.AbsolutePosition - _parentPositionDB.AbsolutePosition; //adjust so moons get the right positions    
    //do a rotational matrix so the normalised position is ralitive to the ellipse.       
    double normalX = (pos.X * Math.Cos(-_radianAngle)) - (pos.Y * Math.Sin(-_radianAngle));
    double normalY = (pos.X * Math.Sin(-_radianAngle)) + (pos.Y * Math.Cos(-_radianAngle));
    normalX += _focalDistance; //adjust for focal point
    normalY *= (_orbitElipseWidth / _orbitElipseHeight); //adjust for elliptic angle. 

    return (float)(Math.Atan2(normalY, normalX) * 180 / Math.PI);
}```

it's now on the crossplatform branch. 
``````
