### ISSUE TITLE
Order Queue

### ISSUE THREAD

**Issue by tsonnier** [Pulsar4xDevs/Pulsar4x#154]
I'm about to start on an order queue, and I could use some input.  Should the orders be Entities, and have datablobs for the types of orders, or should I create a separate class solely for orders?  I'm assuming each player will have its own order queue.  

After that I will create an order processor and a tester.

**Comment by se5a** [comment]
humn...
there's two parts to this I think.
first there's the orders/command that the user gives ie
add something to a construction queue, research queue, give a ship a move order, give a cargo transfer order etc etc.
these need to be stored at the system level.
by storing these as a queue and processing them/checking for validity/legality as part of the system tick, we won't have to worry about race conditions and orders that are given while the system is processing.  
this might need to be a special class, or maybe part of the entity manager, I'm not sure it'll fit as an entity in and of itself. 

once those get processed to check for validity, they'll need to go into an entity's queue. ie a colony's construction queue, a ships move order queue, etc. 
idealy if we can make this bit generic enough then they could be a datablob. else maybe store them as part of the ColonyInfoDB or ShipInfoDB etc.

**Comment by NathanH-** [comment]
I wound up creating different queues for the various order types(task group orders the planetary build queue, shipyard tasks and construction, fire control, etc) for the main branch, they may not be easy to store as just a general order class for everything.

**Comment by tsonnier** [comment]
I agree that the types of orders are fundamentally different between
colonies and ships, and again in combat.  My work is probably not as
developed as yours so I think it best to incorporate your code rather than
mine.

**Comment by NathanH-** [comment]
That work would essentially have to be heavily refactored to fit into the new architecture however. the code for what each order does can be lifted easily enough though.

**Comment by tsonnier** [comment]
Ok, that's something I can work on.

**Comment by se5a** [comment]
Don't get too tied up between the difference between a colony and a ship, try imagine them as the same thing, just one can move, like you've got the movement order checking for the propulsionDB.
jump would have the jumpDB, etc. 
Filter what orders an entity it can accept by what ability datablobs it has.

**Comment by se5a** [comment]
I'm currently trying to expand on this a bit @Shajenko, with the move to a message pump type implementation I've shaken a bunch of stuff up, for example, I've given each entity that will be orderable an OrderableDB which holds a list of orders, specifically for that entity, and it now filters the orders down per system/manager before handing them off to the entities.  I've sort of written out the OrderQueue that you've written and am slowly moving stuff around a bit, I've sort of got it working, but there's a lot of cleanup that I'm trying to do to make it a bit more streamlined, after the mess I've created shifting stuff around and trying different approaches.

**Comment by se5a** [comment]
so how it now works, is when a new component/ship feature gets added, you code an Action, ActionProcessor, and Order. these each derive from their respective base classes. 
when the player gives an order to an entity, a concretion of the specific order is created on the ui side, 
This is then serialized and sent to the messagepump in the ECSLib. (still todo) this will make sending it via TCP/IP or anything we want to do in the future easy.
On the ECSlib side the order gets dequeued from the messagePump and gets deserialised into it's derived concrete class (hopefully - still got to figure out deserialising to a derived concrete class without having a massive switch/case that constantly needs to be added to when new features get added, I'd like to avoid that.).
The order is then passed to the manager, which then turns it into an action and stores it in the ordered Entities OrderableDB.
the managerSubpulse can trigger a specific entity to run any actions that it has, or the OrderProcessor can run actions on all entities for a manager.  

a cool little feature that actions have is a "Lane" which is basically a bitmask. combined with an IsBlocking flag, actions can run on one or multiple "Lanes" and can block other actions in those lanes from running. 
so Movement will block CargoTransfer and VisaVersa (they run on the same lane, and are IsBlocking)
however stuff like turning a componentEntity On or Off (ie a mine, or active sensors) run on another lane, and are not IsBlocking, so those types of orders are free to run at any time. 
this lane is set by the derived Action class, typically in the constructor.

**Comment by behindcurtain3** [comment]
Order queues are working now
