### ISSUE TITLE
Crashes on Startup - Population and shipclass bindinghelpers

### ISSUE THREAD

**Issue by FrederikDiehl** [Pulsar4xDevs/Pulsar4x#17]
Population and shipclass window are trying to bind to VM.Populations and VM.ShipDesigns, but both are null.
This results in a crash (first for economic) with the output "2013-07-31 13:24:32,680 [1] ERROR (Pulsar4X.UI.Handlers.Economics) Something whent wrong Refreshing Cells for Economics summary screen..."

Call stack:
System.Windows.Forms.Binding.PushData (force=false) in 
System.Windows.Forms.Binding.PushData () in 
System.Windows.Forms.Binding.Check () in 
System.Windows.Forms.ControlBindingsCollection.AddCore (dataBinding={System.Windows.Forms.Binding}) in 
System.Windows.Forms.ControlBindingsCollection.Add (binding={System.Windows.Forms.Binding}) in 
System.Windows.Forms.ControlBindingsCollection.Add (propertyName="DataSource", dataSource={Pulsar4X.UI.ViewModels.EconomicsViewModel}, dataMember="Populations") in 
Pulsar4X.BindingHelper.Bind (control={System.Windows.Forms.ListBox}, controlProperty={c => c.DataSource}, dataSource={Pulsar4X.UI.ViewModels.EconomicsViewModel}, dataMember={d => d.Populations}) in /home/frederik/Documents/Projects/Pulsar4x/Pulsar4x/Pulsar4X/Pulsar4X.UI/Helpers/BindingHelper.cs:50
Pulsar4X.UI.Handlers.Economics..ctor () in /home/frederik/Documents/Projects/Pulsar4x/Pulsar4x/Pulsar4X/Pulsar4X.UI/Handlers/Economics.cs:54
Pulsar4X.UI.Helpers.UIController.Initialise () in /home/frederik/Documents/Projects/Pulsar4x/Pulsar4x/Pulsar4X/Pulsar4X.UI/Helpers/UIController.cs:126
Pulsar4X.UI.Program.Main () in /home/frederik/Documents/Projects/Pulsar4x/Pulsar4x/Pulsar4X/Pulsar4X.UI/Program.cs:44

**Comment by Rod-Serling** [comment]
Cannot reproduce this issue on current builds. Please update to a current build and open a new ticket with reproduction steps if issues persist.
