### ISSUE TITLE
Why are we using a 2d list in EntityManager for datablob lookup? 

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#181]
`List<List<BaseDataBlob>> _dataBlobMap`

There's two ways to get datablobs:

```
Entity.GetDataBlob<T>()
EntityManager.GetDataBlob<T>(int entityID)
EntityManager.GetTypeIndex<T>()
   InternalDataBlobTypes[typeof(T)] // (DictionaryLookup)
   _dataBlobMap[int ][int ] //(2d list lookup). 
```

vs

```
Entity.GetDataBlob<T>(int typeIndex)
EntityManager.GetDataBlob<T>(int entityID, int typeIndex)
   _dataBlobMap[int ][int ] //2d list lookup.
```

The second is marginally faster, the first having a single extra dictionary lookup. both are kind of terrible however, since they're both doing two list lookups. 
we're doing a worst case O*N *2 lookup here. 
Why are we not using a `Dictionary<int<Dictionary<int,BaseDataBlob>>` for this? this seems like such an obvious thing that there must be some reason. 
iirc lists have a faster append, but I can't see that we're adding more than we're doing lookups, not to that order. 
Am I missing something?
@SnopyDogy  any idea?

**Comment by DifferentLevelDan** [comment]
I wouldn't call these "List Lookups". Generally a "List lookup" implies a list search, ie enumerating the list until you find a matching value. This operation is, at the worst case (Enumerate front to back, desired item at the back), an O(n) operation, which seems to be what you're implying.

But, as you can plainly see, we're not enumerating the list. We're indexing the list. Indexing a list is simple pointer arithmetic. O(1).

A Dictionary in .NET is implemented as a hash table. Hash tables are also very quick, with index access time APPROACHING O(1), but as the number of entries grow, access time on a Hash table WILL slow down. On a list, it never will. Additionally, O(1) of a list is faster than the O(1) of the dictionary.

The real issue with using the lists is the increased memory overhead and insert/delete operations. When I built EntityManager, I took insert/delete operations into account. EntityManager never performs List.Remove() to prevent reordering of the array (slow), and instead tracks null elements and places future elements in its spot. This helps keep insert/delete operations (close to) O(1) aswell. The memory overhead is unfortunate, but it allows us to keep the memory together to optimize CPU cache usage, without digging through the GC.

**Comment by DifferentLevelDan** [comment]
Feel free to reopen if there's still questions on this matter.
