### ISSUE TITLE
Doing Damage.

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#184]
ideas:

component designs now all have MassVolumeDB.
the volume is currently just half the mass iirc, but at some point this will be able to be defined in the json files.

as far as damage allocation goes, how about looking at doing it like this:
grab all the component volumes and get a total
give each component a chance to be damaged based off the volume vs the total.
roll the dice to see which component gets damaged.
allocate the amount of damage based off the density of the component and the volume (MassVolumeDB has a density value) 
if there's damage points left over, re roll and select another component to do damage to. 
keep doing this until there is no damage left to deal, or you've dealt damage to x number of components, x being based off some value from the total number of components that the entity has. 

components with low density wont take as much damage as those with high density. those with high density will take more damage but damage will be less likely to leak through to other components.

**Comment by se5a** [comment]
@NathanH- 
RE: your comment in IRC about "have to find a way to add all installations a colony has to the dictionary for colony installation placement similar to what ships have"

Consider moving the ShipComponentDictionary from ShipInfoDB into ComponentInstancesDB
since both ships and colonies have the ComponentInstancesDB and it's related enough. 
https://github.com/Pulsar4xDevs/Pulsar4x/blob/ECS-CrossPlatform/Pulsar4X/Pulsar4X.ECSLib/DataBlobs/ComponentInstancesDB.cs

**Comment by ghosta0815** [comment]
On the damage-dealt-to-components topic:
Your calculation proposal sounds reasonable, only I do not understand the part:
> allocate the amount of damage based off the density of the component and the volume (MassVolumeDB has a density value)

Do you want to calculate some sort of hitpoints from the components mass and volume? I think it is hard to find a formula that is fitting for all components.
How about assigning each component a hitpoint value? The mass and volume can give a rough estimate on how much damage a component can take. Later this can also be extended to hitpoints vs certain damage types (physical, plasma, ion, electrical, fire, radiation, mind control, etc. etc. - if damage types are planned/exist...).
