### ISSUE TITLE
Crash when an entity is destroyed.

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#186]
This happens if the entity has a graphic/icon.
currently if an entity has a PositionDB then it will get added to a list in IconCollection (CrossPlatformUI/SystemView/IconCollection.cs)

so far there is no way for the ui system to be alerted if an entity is destroyed, so the ui tries to draw an non existing entity. 
there's also no way to check if an entity is valid from the ui either, and it's also probably not a good idea to check each item every refresh either, since we want to keep the refreshes as fast as possible. 

We could maybe do a GetAllEntitysWithDatablob() each frame, instead of keeping a list in the ui. this would prevent the problem, but I'm not sure how efficient it'd be. 

we could cause it to throw an exception, then catch it. but that seems a bit smelly.

**Comment by se5a** [comment]
yeah I'll try GetAllEntitesWithDatablob instead of storing a list. and see how it works out.

**Comment by DifferentLevelDan** [comment]
> there's also no way to check if an entity is valid from the ui either

`if (entity?.IsValid == true)
{
    // Entity is valid.
}`

Also,

```
// Filter entityList to only active entities each frame.
entityList = (List<Entity>)entityList.Where(entity => entity?.IsValid == true);
                
foreach (Entity entity in entityList)
{
    // Draw entity.
}
```

> it's also probably not a good idea to check each item every refresh either, since we want to keep the refreshes as fast as possible.

GetAllEntitiesWithDatablob will be significantly slower. If performance is key here, use a cache list like you were.

> so far there is no way for the ui system to be alerted if an entity is destroyed

Not a bad idea to implement some events on entities/entitymanagers.

> we could cause it to throw an exception, then catch it. but that seems a bit smelly.

It is smelly.

**Comment by ghosta0815** [comment]
Why not calling the ViewModel_PropertyChanged Event of SystemMap_DrawableView when an entity is destroyed?
It calls the _iconCollection.Init and populates a fresh List. Is it to slow?

If this is not possible, we need to store a reference to the entity in each IconBase and include some delete mechanism. Like a delete event that is called when an entity is destroyed.
