### ISSUE TITLE
Ship Movement stuff. 

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#200]
I had an idea for doing movement which could add some interesting gameplay, and maybe allow a bit more flexibility in how stuff gets balanced wrt defending a system, and ships maintenance, crew rest, and fuel costs. 

basically, any entity in space is orbiting something unless it's making way. 
We'll have the typical aurora translational move, (lets call these engines Alcubierre drives)
when the drive is off off, i.e. not making way the ship will orbit whatever body the ships position puts it in the sphere of influence of*
However since the JumpPoints are static, the ship will have to be expending fuel to stay at the Jump point, making the points a bit more expensive to constantly defend. 

putting ships/satellites into highly elliptical orbits with the JP at the apoapsis would increase it's linger time at the JP with least fuel used. 

If/when we want to make things a bit harder for our selfs (to code) we could add newtonion thrusters as well, and ships would keep their newtonion vectors while under Alcubierre warp. they'd have to expend some DeltaV going from one orbit to another even with the Alcubierre.  (though there are some tricks to alleviate this, such as using warp to put the ship into a position where it can use the body to grav brake, this is not something I'd want the player to have to worry about, but maybe once ship captains get experience they can use this technique )

To make this work we'd have to implement:
Calculating the sphere of influence for each body - this should be just a radius calculated by the mass of the body, or the primary star. 
Add code to have ships linger in Alcubierre warp at a static position using fuel. 
Add UI stuff to allow the player to put the ship into an elliptical or other orbit.

**Comment by ghosta0815** [comment]
Mixing newtonian physics with non-newtonian physics might be quite confusing for the player as Newtonian physics on its own is not very intuitive. Also from a coding aspect this is not an easy task:

Consider e.g. interception paths: It is quite fun if you are doing this for a few ships (Kerbal Space program is doing this very well) but you have to do this for a multitude of freighters, civilian and military ships that are traveling a few dozen times between planets and bases.

**Comment by se5a** [comment]
yeah most of it would need to be handled by the unitAI so the player wouldn't have to worry about it too much, and some of it could be abstracted away a bit. 
I guess mostly it gives a somewhat more believable movement mechanism than auroras movement. 

for now we really just need to implement the translational move (was done, mostly) and dropping a ship into an orbit at it's target body (was sorta done, I think...) the rest are stretch goals. 
Though changes to how orders and actions, the "done" code has to be revisited. 

I got the idea from a ksp mod: http://forum.kerbalspaceprogram.com/index.php?/topic/90899-13-alcubierre-warp-drive-stand-alone/

**Comment by se5a** [comment]
I've actually implemented a lot of this, and it seems to work from a gameplay and ui pov. 
Ships translate from one point to another, the velocity vector they have before they start the translation is used to calculate an orbit around a target body once they've arrived. 
 - Currently the saved velocity vector is relative to the body it was orbiting, probably it should be relative to the star.  (There is now an option for this)
 - Currently there are no Newtonian thrusters/move, I'd like to implement that at some point, it'll give the player more options on the orbits. ie translate to a point then adjust the orbit.
it  may not be as hard as we thought to code, there is a calculation for hoffman transfer in the lib now, and I've implemented constructors on the orbitDB that'll take position and a velocity vector to get an orbit.   (the basics of this are now implemented, but probably needs expanding on)
 - The UI still needs a bit more polish, and should probably have the ability to choose a point or time for the translation to start, currently you have to step through time till the ship is at a point in it's current orbit that you'd want.  
 - There's still some bugs with the code, in some positions the ship will jump from its position to another spot on its orbit after translation end/new orbit given, and the prediction math for calculating an intercept to a target body could be cleaned up.  
 - I'm thinking of dropping the "expend fuel to stay in one spot" mechanic and see how defending JP's by using elliptical orbits works out - once we finally get that far.

**Comment by agm-114** [comment]
Mostly completed.
