### ISSUE TITLE
Crash on 1 month timestep

### ISSUE THREAD

**Issue by agm-114** [Pulsar4xDevs/Pulsar4x#250]
Set timestep to one month, then increment a single month and the game crashes.

> System.InvalidOperationException
>   HResult=0x80131509
>   Message=Collection was modified after the enumerator was instantiated.
>   Source=System
>   StackTrace:
>    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>    at System.Collections.Generic.SortedSet\`1.Enumerator.MoveNext()
>    at System.Linq.Enumerable.Min[TSource](IEnumerable`1 source)
>    at Pulsar4X.ECSLib.ManagerSubPulse.GetNextInterupt(TimeSpan maxSpan)

**Comment by se5a** [comment]
Does this happen every time, or just sometimes?

**Comment by se5a** [comment]
Tried a bit more to reproduce this but was unable. 
without being able to step through the stack and inspect the variables I can only guess at where this is happening (or where the cause of this is happening) and more importantly I can't see *how* it can happen.  
I'm assuming you were running it single threaded (which is default). 

From what you've posted I'm guessing that it's the QueuedProcesses SortedDictionary which is having the issue. somewhere we're looping through the keyvalue pairs of this and while doing so adding or removing said key value pairs. 
I can see where we're looping through a list in the *values* of said dictionary (the values contain a collection themselves) and then adding to the parent QueuedProcesses dictionary, but this *should* be fine.

**Comment by se5a** [comment]
So this does not apear to be happening in the current dev branch, however the ui does hang in these conditions, created a new issue for that #256
