### ISSUE TITLE
MXLinux: compilation from terminal without IDE

### ISSUE THREAD

**Issue by Houkime** [Pulsar4xDevs/Pulsar4x#255]
Hi. Reporting some results.
I wanted to try out Pulsar and have managed to run it from sources on a clean MXLinux machine.
There is no requirement to have a specific IDE - there is a simpler IDE-agnostic purely terminal way to compile and run, and it can be used for automatic builds.

## Instructions (for a Debian-based OS)

Testing OS was MXLinux 19 which is based on Debian 10. 
I used a clean virtual machine to keep my Arch install away from MS stuff. Order is important because of xbuild-msbuild conflict described below.

```
sudo apt install apt-transport-https dirmngr
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/debian vs-buster main" | sudo tee /etc/apt/sources.list.d/mono-official-vs.list
sudo apt update
sudo apt install msbuild
sudo apt install mono-complete libsdl2-dev
sudo apt install nuget
git clone https://github.com/Pulsar4xDevs/Pulsar4x
cd Pulsar4x/Pulsar4x
nuget restore
msbuild Pulsar4x.sln -t:Build
mono Pulsar4X.ImGuiNetUI/bin/Debug/net47/Pulsar4X.ImGuiNetUI.exe
```

## Notes

* first few commands are from here: https://www.monodevelop.com/download/#fndtn-download-lin-debian
* `mono-xbuild` is currently being deprecated by Mono (unfortunately) in favor of Microsoft `msbuild` which is somewhat less readily compilable from sources (if avoiding preexisting dotnet binaries) and is not in official repos.
* because of `xbuild` being deprecated, it doesn't support newer .csproj  formats and never will. 
* New Pulsar4X build files are no longer compatible with `xbuild` and require a bulkier `msbuild` route.
* Old Pulsar4X build files ARE compatible with `xbuild` but seems like they are no longer compatible with Pulsar sources.
* It is important to install `msbuild` before `mono-complete`. `mono-complete` includes `mono-xbuild` and if installation process of `msbuild` sees preexisting `xbuild` it tries to do sth with it and it results in a file conflict. Conflict does not arise if `msbuild` is installed first and only then comes `mono-complete` with `mono-xbuild` included.
* MonoDevelop uses `msbuild`. Process here is identical to what you will have with an IDE but with less overhead and no clicks.
* The above fact also means that when installing MonoDevelop you need to ensure that `msbuild` is installed before `mono-xbuild` (MonoDevelop has an indirect dependency on `mono-xbuild` so you can't omit the latter). You might want to install `msbuild` separately first.
* Build process rises around 100 warnings, but no errors.

## Screenie

![pulsar_screen](https://user-images.githubusercontent.com/32805122/73322851-66999180-423d-11ea-896e-fabaf54254c8.jpg)

## Behavior

There are some small weird details in how UI operates (may report as separate issues when have time) and i have nothing to compare it with, but overall seems to be working fine.

## Further Notes

Maybe if I _really_ like it I will fork it and port to syntactically-similar but infrastructurally different [Vala](https://en.wikipedia.org/wiki/Vala_(programming_language) ) to make it less cumbersome.  
Right now i can't even post Pulsar4X to [AUR](https://aur.archlinux.org) (despite automated builds being possible as shown above) because of MS infrastructure it relies upon.  
Although technically I can (there are packages for mono in official Arch repos, and also msbuild and nuget in AUR), i'm sure not the one that wants to maintain and debug such an install.  
If you are interested in having and maintaining an AUR package (for Arch Linux, Manjaro and other Arch-based distros), I can prepare an initial PKGBUILD for you to own and maintain.

**Comment by se5a** [comment]
Ah nice work. 
yeah the changing csproj formats is a bit of a pain, I forget exactly why I decided to update to the newer format, but it must have seemed like a good idea at the time (I do remember it being a bit of a pain).
Another option is to go full dotnet core, but I'm a bit hesitant for a number of reasons, one big one is that debugging options are/were severely lacking in monodevelop, which was my primary IDE for a long while, however I've been rather disappointed in how MS has managed MD since it took over. 
Another reason was that there didn't seem to be an easy way to hide the console window when launching a dotnet core app.

Edit:
I should also point out that most the warnings are just placeholder variables that are not used anywhere. I should go through and tidy some of that up at some point though.

**Comment by se5a** [comment]
Added a link to this from the readme

**Comment by agm-114** [comment]
https://github.com/Pulsar4xDevs/Pulsar4x/wiki/Compilation
Added to the wiki

**Comment by agm-114** [comment]
Information moved to wiki.

**Comment by se5a** [comment]
@Houkime FYI: I've shifted the DevBranch over to .net core 2.2
