### ISSUE TITLE
Warp move ship icon doesn't face the correct direction. 

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#259]
When a ship is doing a translation/warp move, the ship icon doesn't point in the correct direction. 
![image](https://user-images.githubusercontent.com/1490538/75632248-0c865480-5c5f-11ea-9c4a-2e922e02a80a.png)

This could maybe be an easy one for a new contributor.

**Comment by behindcurtain3** [comment]
This is fixed now
