### ISSUE TITLE
Flesh out Json mod files.

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#276]
These basically describe the ingame components, and installations that can be designed, tech that can be researched, minerals, materials, etc.

This is a good issue for somone who has an eye for balance and can come up with interesting gameplay mechanics that work within the hardcode framework.
The game is looking to be more "hard" scifi than Aurora (i.e. we have newtonion movement and real instead of TN minerals) numbers for e.g. engine thrust, component weights, fuel use etc. should have some basis on reality. 
 

#71 could help with this but is not a requirement. (once you've messed with the json files a little bit, they're not too hard to work with raw)

**Comment by somebody1212** [comment]
Atmospheric gas data done. Unable to create pull request currently, GitKraken's complaining about permissions. Do I need to fork and then do it, or are we creating a branch for this?

(well, I say it's done - I'm missing the cyanopolyynes and polycyclic aromatics on Titan, but most of the rest is there)

**Comment by se5a** [comment]
Yeah do a fork and a pull request.
annoyingly github wont allow pullrequests without a fork

**Comment by somebody1212** [comment]
Fair enough. No problem.

**Comment by behindcurtain3** [comment]
Made enough progress on this it can be considered closed now I think.
