### ISSUE TITLE
Get rid of GUID as object IDs and use something lighter. 

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#305]
I feel that using GUID is a bit overkill, and a little too heavy for what they're doing in pulsar. 

a 64bit int should be more than sufficient.
if we do something handmade it might be worth using the first few bits to identify the type of object (ie ship, missile, planet etc)
and the rest pseudo randomly generated. 
Grumpy old Wombat suggests using a Cryptographically secure rando would reduce the chance of collisions enough that we wouldn't need to check. 

This could be potentially a massive job, or if we're cleaver might be relatively painless ie:
Create a new ID object with the same functions that GUID uses.
Find and replace GUID with our new IDObject. 
Edit the IDObject.NewGuid() method to require whatever we want to pass it for the object type and  rando seed.
RenameRefactor NewGuid(objtype, seed) and any other methods that don't quite fit what they now do.

**Comment by behindcurtain3** [comment]
Ever played factorio? They have a good system to handle this. It scopes everything in namespaces and then a unique string id. So for the base game it'd be like: `base.flamethrower` 

It's super easy to extend and you instantly know if the thing is base game or what mod it is and what it actually is also!

**Comment by behindcurtain3** [comment]
The documentation: https://lua-api.factorio.com/latest/index-prototype.html

Notably, everything in the game uses their prototype system and the base game loads just like a mod would.

**Comment by behindcurtain3** [comment]
This is good now, we have int's for the ID's and string for UniqueID's
