### ISSUE TITLE
Turn Cycle button not working properly

### ISSUE THREAD

**Issue by Cones-Bones** [Pulsar4xDevs/Pulsar4x#308]
The turn cycle button completely breaks the game

1. Click the |> button

[https://i.ibb.co/93jdjNg/image.png](url)

**Comment by se5a** [comment]
Tried to replicate this but failed.
Need more info, ie what time span etc. settings.

**Comment by behindcurtain3** [comment]
I think this has been fixed, if not feel free to re-open.
