### ISSUE TITLE
Reduce the number of NameIcons on the map by combining colony into planet. 

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#309]
The planet NameIcon would have extra chars or icon to indicate that it has a colony.
i.e.: ![image](https://user-images.githubusercontent.com/1490538/174513102-3898f686-a0ab-4736-a14f-4cb43294474d.png)
We could maybe further this by reducing this further into SOI systems, eg, EarthSOI (P,M,C,S6) 
would indicate a planet, a moon, a colony and six ships. 
Zooming it would separate this into it's individual name icons. 
we could use small images instead of letters. 
Planet and Colony actions should be merged down into a single window and or tabs etc.

**Comment by se5a** [comment]
Looks like I've(or somone) attempted to do something similar to this in the past, 
There's a dictionary of Subsames here: https://github.com/Pulsar4xDevs/Pulsar4x/blob/DevBranch/Pulsar4X/Pulsar4X.ImGuiNetUI/MapRendering/Icons/NameIcon.cs#L49

And Draw iterates through them here: 
https://github.com/Pulsar4xDevs/Pulsar4x/blob/DevBranch/Pulsar4X/Pulsar4X.ImGuiNetUI/MapRendering/Icons/NameIcon.cs#L252

I don't think subnames dictionary are ever added too though.
One problem here is we start getting into the fog of war problem and who can see/knows about what, which has never really been solved.
that being said it might be worth ignoring that for now and just adding everything.

**Comment by behindcurtain3** [comment]
Can probably close this now?
