### ISSUE TITLE
Move the Minerals dictionary from SystemBodyInfoDB to it's own DB

### ISSUE THREAD

**Issue by behindcurtain3** [Pulsar4xDevs/Pulsar4x#339]
It seems like minerals a good candidate to separate out into it's own DB.

**Comment by se5a** [comment]
```
public class MineralDepositInfo
{
    public long Amount { get; internal set; }
    public long HalfOriginalAmount { get; internal set; }
    public double Accessibility { get; internal set; }
}
public Dictionary<Guid, MineralDepositInfo> Minerals { get; internal set; }
```

There are some minor pros to doing this and I can't see any major cons. 
I think it'll be easier to do than I initially anticipated as well.


It'll also mean the mining processor wont be pulling a whole bunch of other data into the cashe just to run the mining, which would make it a bit more efficient, not that mining is ever likely to be a bottleneck. 

Might as well go ahead and do this.
