### ISSUE TITLE
TypeStore FreeVolume isn't updated

### ISSUE THREAD

**Issue by behindcurtain3** [Pulsar4xDevs/Pulsar4x#347]
When new items are added to a `TypeStore` in a `VolumeStorageDB` the `FreeVolume` is never updated.

**Comment by se5a** [comment]
Supposed to interact with it via the CargoExtensionMethods
I should have at least put comments in there to that effect. 
There may be a way to use Attributes to restrict this which might be worth looking at.

**Comment by behindcurtain3** [comment]
Thanks, that fixed it. It might help to make properties like that internal so they aren't visible in the UI project. I'll start with that one!
