### ISSUE TITLE
Refactor Entity Creation to Use Factories

### ISSUE THREAD

**Issue by DifferentLevelDan** [Pulsar4xDevs/Pulsar4x#376]
**Issue Description**

Currently, entities in the codebase can be created without going through a factory, leading to potential issues with entity validation. To standardize the entity creation process and ensure that all entities meet validation criteria, we should refactor the code to require that entities be created through factories.
Goals:

    Identify all places in the code where entities are being created without using factories.
    Implement factory methods for these instances.
    Include entity validation logic within these factory methods.
    Update existing code to utilize these new factory methods.

**Acceptance Criteria:**

    All entities are created through factory methods.
    Entities created without using factory methods should trigger a warning or exception.
    Existing unit tests should pass, new tests should be added to cover the new logic.

This refactor aims to make the entity creation process more robust and maintainable while ensuring that entities meet all validation criteria before they are used.
Labels

    Refactor
    Factory Pattern

**Comment by behindcurtain3** [comment]
I checked everywhere that calls `Entity.Create()` and they are all in factories. The constructor for the `Entity` class is private and not used anywhere except the `Entity.Create()` method.

I think we can close this.
