### ISSUE TITLE
Jupiter's moons are in the wrong position on game start

### ISSUE THREAD

**Issue by behindcurtain3** [Pulsar4xDevs/Pulsar4x#388]
Toggle SM Mode, they are off in the wild. Run a timespan that updates the orbits and they'll be in the correct place around Jupiter again.

**Comment by se5a** [comment]
Fixed.
The moons had been given moon position + parent position at start (eg absolute position) when they should have been given relative position. 
Jupiter also had Saturn's moons, which i also fixed.
