### ISSUE TITLE
TreeHierarchyDB Children and Parents aren't cleaned up if the DB is removed from the Entity

### ISSUE THREAD

**Issue by behindcurtain3** [Pulsar4xDevs/Pulsar4x#394]
If an OrbitDB is removed from an Entity, the DB can still be referenced by the Parent or Children of other DB's in it's hierarchy. This will crash the game in the OrbitProcessor when it reaches the entity that now no longer has an OrbitDB.

**Comment by se5a** [comment]
Related:
Orbit processer doesn't need to walk through the tree anymore, and should be faster if we don't. ~That is on my todo shortlist.~ this is now done. 
Position and orbits should always have the same parent, and I think children, there's probably something we can do to merge these somehow.

**Comment by se5a** [comment]
Can you write a test for this? Looking at the code, TreeHiraechyDB should handle this correctly.

**Comment by behindcurtain3** [comment]
I've re-confirmed this is an issue now that combat works. 

To trigger it:
Shoot down one of the target drones, then check the PositionDB of Luna in the debug window. It will still show 4 children even though one of the drone entities no longer exists in the EntityManager. You can also check the PositionDB of Earth and see all the beams that were fired in the children.
