### ISSUE TITLE
Need to get list of TG by StarSystem. 

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#40]
Should be a dictionary in Faction to get TaskGroups by Starsystem.

Then places like UI.Handers.TaskGroup.AddTaskGroupsToList() should be cleaned up.

**Comment by se5a** [comment]
And Waypoints.

**Comment by Rod-Serling** [comment]
This seems to be an old issue.

To get a taskgroup from a StarSystem, use the entityManager.
