### ISSUE TITLE
Many tests fail

### ISSUE THREAD

**Issue by whaleberg** [Pulsar4xDevs/Pulsar4x#50]
Many of the existing tests fail on my machine with various exceptions, mostly `NullReferenceException` 

`CargoOrdersTest`
`CollierOrdersTest`
`ColonyOrdersTest`
`ComponentLoadUnloadTest`
`OrdnanceTest`
`TaskGroupFuelOrdersTest`
`TaskGroupMSPOrdersTest`

all fail with various `NullReferenceException` 

`Load_GameState_From_JSON` fails with this:

> `Newtonsoft.Json.JsonSerializationException` : Cannot preserve reference to array or readonly list: System.Decimal[]. Path 'Factions.$values[0].ComponentList.CrewQuarters.$values[0].minerialsCost.$values', line 85

`FactionSystemTest` gets stuck in an infinite loop at line 1573 of SystemGen
```
                do
                {
                    luckyStar = system.Stars[m_RNG.Next(system.Stars.Count)];
                } while (luckyStar.Planets.Count != 0);
```

`SimulationTest` loops forever as far as I can tell, and that seems to be by design.

Are any of these tests passing for other people?  If it's just my machine I need to figure out what's different.  If it's not my machine, they should probably be made to pass.

**Comment by NathanH-** [comment]
Shiptests are all essentially deprecated at this point, so if something broke then don't worry about it unless they stop a compile.

**Comment by Rod-Serling** [comment]
As discussed on IRC, these tests failing is an active issue even if the tests themselves are depreciated. The tests should either be updated or removed entirely before this issue is closed.

Whaleberg, I'd love to see you on IRC sometime! Freenode channel #Pulsar4X

**Comment by NathanH-** [comment]
nevermind, I was wrong, critical parts of functionality were broken during rewrites, and this could have implications for Pulsar proper, so I'll have to run those down and fix them.

**Comment by NathanH-** [comment]
All the shiptests should be fixed on the shipyard frontend branch now, that will be merged later. the store bugs are still present, not sure where we are on JSON, and a new bug relating to a lack of missile icons just popped up.

**Comment by Rod-Serling** [comment]
The current JSON was written 3 years ago by @richclement and doesn't seem it ever reached a level of functionality. I would consider it depreciated and should be removed for reimplementation at this point.

I believe our current plan is to use JSON to load static game information when a user starts a new game. This will then be saved/loaded from a SQLLite database for the specific savegame.

**Comment by DifferentLevelDan** [comment]
wontfix due to it being an issue with the legacy master branch, where development no longer occurs.
