### ISSUE TITLE
ECS: Facilities. blobs, staticdata, json, factories, processors, etc.

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#69]
This should in general look fairly similar to components.

**Comment by se5a** [comment]
Ok I've done a bit of this. Want someone to sanity check it before I continue.
installations is the word Aurora used so i've kept with that. 
in a nutshell I've got:

an enum of InstallationAbilityTypes

InstallationSD which contains all the generic info as well as a dictionary containing the InstalationAbilityTypes as a key and an int for the amount of ability as a value. 

InstallationDB which is a dictionary of all the installation types a colony has as a key, and the number of these facilities as a float value. float because they can be broken up for transport.
 
the colony Entity will have one of these InstallationDBs and as installations are build they will get added to the InstallationDB for that colony.  

The installation has a method/function to return an int of the ability of a given type:
public int TotalAbilityofType(InstallationAbilityType type)
This should maybe be in the processor? and needs to check pop requirements as well...

It's fairly simple, and gives a bit of flexibility modwise. ie you can create facilities with multiple ability types in the json data.
The ability types could be expanded to include penalties such as increasing EM signature etc. 
The downside is all the abilities are in one blob, instead of having one blob for each ability. not sure how bad that is...

**Comment by SnopyDogy** [comment]
Two things, 
1) I would change AbilityAmount in InstallationSD to BaseAbilityAmount to reflect the fact that it will be modified by research/faction modifiers.
2) I agree the TotalAbilityofType() function should be in a processor somewhere. You could however cache the result in the datablob. I.e. there is a processor which runs as a result of specific events (new research occurred, insufficient population, etc.) and updates the total ability amounts for a installation (or better still do it at the colony level) and then have the installationDB (or better still colonyDB if we do it at the colony level) cache the results so we are not re-calculating it every time we need it.

**Comment by SnopyDogy** [comment]
Oh, I just thought o something... Where have you specified the costs of the installation (wealth + mineral costs)?

**Comment by se5a** [comment]
Done, Done, and Done!
a processor has been added for Mining, it's messy at the moment but you should get the general idea.
I want to try a construction processor next, this is going to require some more blob work, I'm going to have to think about/play around with.

**Comment by se5a** [comment]
A lot more work has been done on this. finally there is a population check processor!

There is most of the construction processor done too, what's left with that is to have it check and use the required resources from the colony stockpile, and wealth when we have some wealth in.
I'd like to try get the Construction processor to be a bit more generic and use the same processor for ordnance and fighter construction. 99% of it is the same.

Another thing we need to decide is how we're going to do shipyards. in aurora they were a bit special, being somewhere between an installation and a ship.

**Comment by se5a** [comment]
The current implementation needs to be re-written to match what I'm doing with components.
Closing and creating a new issue.
