### ISSUE TITLE
Pulsar4X Logo

### ISSUE THREAD

**Issue by SnopyDogy** [Pulsar4xDevs/Pulsar4x#7]
We could use a proper Logo and some unique graphics for the Splash Screen and About Box. 
Relevant forms are AboutBox.cs and StartupSplashScreen.cs.
The Splash Screen will also need some matching colors for Text and Progress bar.

No C# coding skill necessary for this, just winforms "WYSIWYG" layout/design work.

**Comment by Rod-Serling** [comment]
What's the current status of this issue? Is our current icon sufficient?

**Comment by Josephine98** [comment]
If you give me a list I can throw toguether some icons and graphics assets

**Comment by Michael1993** [comment]
This should be closed, because Pulsar 4X now has a logo.
