### ISSUE TITLE
ECS: Faction attributes tied into research.

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#70]
Faction has some attributes that can be modified when research has been done.
build points, research rate, etc etc.

**Comment by se5a** [comment]
Copernicus has done some work on this, nice work!

One thing I'm unsure of though.
Aurora does the points a bit.... odd.  for example the construction rate  formula for Aurora is:
Formula: (Racial Factory Construction Rate) * (Sector Governor Factory Production Bonus * 0.25) * (Planetary Governor Production Bonus)

I wan't to change it so:
Formula: (InstalationConstructionRate * FactionModifier * (SectorGovernor * 0.25) * Planetary Governer)

So instead of the base coming from the faction, it comes from the Installation. 
The Faction Abilities would become modifiers/multipliers and be floats sitting around 1.0.

Thoughts?

Eventually I'd like to have a race modifier in there as well, but lets keep things simple for now.

**Comment by SnopyDogy** [comment]
Your Formula is how I would do it too. And I agree about the race modifier.

**Comment by se5a** [comment]
Or maybe the different bonuses should be added together, then the result multiplied by the installation Rate. 
ie;
faction bonus = 1.02
planetGov = 0.05
sectorGove = 0.04
total bonus = 1.11
colonyInstallationConstructionPoints = 110;
totalPoints = 110 * 1.11 = 122 (rounded down to an int)

**Comment by se5a** [comment]
I got talked out of adding them. 
It can cause some funky math that can be hard to balance. it's better to just multiply it all together.

**Comment by DrCopernicus** [comment]
Definitely agree with moving the base factors to the installations. That might allow for some sort of upgrade infrastructure mechanic, as well as capturing enemy installations which keep the same rate. Also keeping faction abilities as an additional multiplier would be cool for species that specialize in mining, factory production, etc.

**Comment by se5a** [comment]
I went ahead and made the changes to floats.

**Comment by se5a** [comment]
I've made the InstallationAbiltiessType more generic, calling it AbilitiesType and putting it into the FactionAbilitiesDB.cs file 
I've changed the DataBlob to have a dictionary of AbilitesType,floatValue instead of a different field entry for each of ability. this will make it easier to access the ability bonus we want in code. 
There's a couple of abilities that are still there that I'm not sure how we're going to handle yet, so they are left as separate fields
