### ISSUE TITLE
ECS: Reference entity or guid in ui? 

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#72]
Which way are we going with this? I can do the legwork and get it building again if you've gotten busy snopy.

**Comment by SnopyDogy** [comment]
It needs to be a Guid I think. If the UI has a deep copy of the entity then that would be a different reference, which would not work with the message books (failed dictionary lookup). But the Guid should be the same even for a deep copy of the entity, so the dictionary lookups will always work.

Having said all that I think rod was talking about removing the message books and working with just two message queues, an in queue and an out queue. Might want to talk to rod about how UI comms will work before going too far.

If my changes have stopped the UI from compiling tho then go ahead and fix that.

**Comment by se5a** [comment]
I fixed it not building. ended up being pretty simple to fix that. it's currently not running though when starting the ui, iirc the manager is null when checking if an entity is valid. 
I'll leave this open till Rod has got a bit further on the comms and we're back to running.

**Comment by se5a** [comment]
...he wrote, accidentally clicking the "Close and comment"  button.

**Comment by Rod-Serling** [comment]
With the ECSLib acting as an API Library, it can return a full entity reference. The ECSLib provides PublicAPI functions for manipulating the Entities in a controlled way. If this answers your question, please close this issue.

**Comment by se5a** [comment]
Yeah the Api work has answered the question
