### ISSUE TITLE
ECS: GUIDs as references in json files

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#73]
Been thinking about this, as it's a little clunky on the mod/data side.

Wondered if we could use just the names in the json files and reference those, then have the json importer turn the name into a deterministic guid. 
went looking to see if this had been done before and found this:

http://stackoverflow.com/questions/2642141/how-to-create-deterministic-guids

Snopy? this is kinda your baby.

**Comment by se5a** [comment]
The main reason we're using guid is so that we can change the name in the middle of a game (ie fix a spelling mistake etc) 
whether the pros outweigh the cons is arguable, but it's probably not a big enough argument to argue. 
with the json tool the cons are diminished.

This should maybe be labeled as wont fix?

**Comment by SnopyDogy** [comment]
It's not just so you can re-name during the game, but also so one set of data files can overwrite another. An example of this would be A modder wanting to replace the names of existing minerals. of we link by the name then every place the mineral was used in other static data (both the modders and other peoples, including the official data) would need to be updated. Thus making it harder to have a stand alone mode that modifies official parts of the game, or extends other mods, etc. 

The Json tool should make it easy to use the Ids in the json but present names to a modder.
