### ISSUE TITLE
ECS: Internalise functions/methods 

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#76]
Many functions and methods are set to public, these should be set at least to internal, and some tests moved into a test folder inside the lib.

**Comment by johanvergeer** [comment]
Hi Rod-Serling, 
I am pretty new to software development and I am looking for some open source projects to work on. 
Do you think this would be a nice job for a freshman to get started with. 

I took a look at the game and the code and it looks like a nice project to contribute to. 

I also noticed that the website for this project is offline. Could you tell me why that is?

Best regards, 
Johan Vergeer

**Comment by se5a** [comment]
Yeah looks like  Rod's gone awol.
if you're interested in helping, probaby best bet is to catch me on IRC: #pulsar4x on Freenode.

**Comment by johanvergeer** [comment]
I will have to figure out how to get on IRC first. If you know a good manual/tutorial for that, it would be awesome. Else please give me some time to figure that out.

**Comment by Auranis** [comment]
Hi se5a,
I've been lurking this project for a while and I think I'd also be interested in contributing.
What times are you usually on IRC? (I'm not familiar with it so if time isn't a factor, all the better)

Many thanks.

**Comment by se5a** [comment]
I'm lurking on IRC most the time, just log in and see if I reply, I always say that the 'I' in IRC stands for 'Idle' - I may not answer right away, so don't just leave after five min.
