### ISSUE TITLE
ECS - Save Game Size

### ISSUE THREAD

**Issue by SnopyDogy** [Pulsar4xDevs/Pulsar4x#77]
Rod was talking about the save game size getting rather large on IRC today, I thoud i'd open an issue for it.

From IRC (all Rod-Serling):
> Bad news is our savegames are already kinda big.
> A game with 100 systems, 0 ships, 0 colonies, 0 missiles, and 0 static data is averaging around 36.8MB
>Sample size 10, Min: 32.5, Max 41.6
>That's with the JsonSerializer set to Formatting.Indented
>With Formatting.None, we drop down to 18.4MB average, Sample size 10, Min: 16.89, Max 22.7
>Which is a good saving, but still fairly large.
>7Zip gives them a 10% Compression Ratio though, meaning most saves are under 2MB. We might want to consider compressing before saving.
>LZMA SDK can be found here:
>http://www.7-zip.org/sdk.html
>BSON showed similar. 17.1MB average, Sample size 10, Min: 14.4, Max: 19.9 About 10% compression using LMZA (18.5MB for all 10 files compressed)

So a few things to note here:
1. With regards to tabs, yes we should removes those from release version of the game. 
2. Long term we should keep the advice on this page in mind: http://james.newtonking.com/archive/2009/10/23/efficient-json-with-json-net-reducing-serialized-json-size. The default value stuff especially could reduce the size by a lot.
3. When talking about compression I think we should look at System.IO.Compression first. It uses zlib which is close in compression size but much faster then LMZA.
  * Link to compression in .net: https://msdn.microsoft.com/en-us/library/ms404280(v=vs.110).aspx
  * We should use the gzip or deflate streams, as they should work as drop in replacements for the file stream we are currently using, see here: https://msdn.microsoft.com/en-us/library/system.io.compression.gzipstream(v=vs.110).aspx, or here: https://msdn.microsoft.com/en-us/library/system.io.compression.deflatestream(v=vs.110).aspx
  * Link for LZMA vs. Zlib comparison: http://leadsift.com/7zip-gzip-compression-speed/   

Finally I thought I would add some info on the save game size of other games here to help put things in perspective (sourced from my own PC or quick web searches).

| Game  | Save Size (MB) | Notes |
|------------- | ------------- | -------------|
| Age of Empires 3  | 1.7 |
| Company of Heroes | 18 - 24 |
| Civilization 5 | 0.5 - 2.3 |
| Skyrim | 3.1 - 7.3 |
| Terraria (world size) | 5 - 48.5 |
| XCOM - Enemy Within | 0.15 - 1.5 |
| Total War: Rome 2 | 1 - 8.5 |
| Total War: Shogun 2 | 1.6 - 2.2 |
| Minecraft | 17 - 100 | World size, with some worlds 1500+ |
| Dwarf fortress | 12-25 | Compressed, small-ish worlds. |
| Aurora |  34.7 | v.6.4.3, Steve's reference game (includes static data too) |

Looking at the numbers above, a 2MB save game file (using compression) isn't too bad, especially when compared to other open world/sandbox games.

**Comment by SnopyDogy** [comment]
Some more info from Rod on this issue:
>  Got GZip compression working.
> Looking at < 10% compression
> For indented formatted JSON
> 10 Indented uncompressed save files are 390MB, 10 indented compressed save files are 32.2MB
> Same save files of course, literally saved 10 games twice, once compressed once uncompressed.
> Decompression working with GZip.
> Decompression is really easy. Just attempt to decompress. If it's not compressed, it wont fault.
> ...
> Uncompressed saving took 2131ms, Compressed Saving took 2201ms
> Loading: Uncompressed: 5045MS, Compressed: 4281MS
> ...
> Try 2, Uncompressed: 4289MS, Compressed: 3826MS

Looks like Gzip is the way to go here.

**Comment by Rod-Serling** [comment]
While we should continue to monitor save file sizes, I believe that we currently have fairly small save files with compression. With 100 systems, we're currently looking at about 3.5MB files compressed.

Our compression and decompression is fast and achieves a 10% compression rate.

We will continue to monitor save files sizes, I am closing this issue as no work needs to currently be done to fix this problem.

**Comment by Antagonistic** [comment]
A little late in the game, but I would like to advise taking a look at BSON encoding.  Should be able to slot it instead of JSON easily.

**Comment by Rod-Serling** [comment]
BSON is actually sometimes larger. It's not really a compression aspect. Currently I don't think there's an issue with using the Gzip'd JSON without indents. 3.5mb is very small for 100 systems.
