### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by Antagonistic** [Pulsar4xDevs/Pulsar4x#8]
We need one.

I guess not highest priority since alpha we can distribute as a zip, but will need one eventually.

I advise looking at something like WIX, but whatever we use would be best if its cross-platform.

**Comment by Rod-Serling** [comment]
While being cross-platform would be great, I don't think we're really in the position where we can support more than the windows platform. I can make an installer pretty easily, for windows. If a linux user wants to play, I think they're better getting it working themselves.

While this might seem harsh to linux users, they are generally a bit more computer-savvy.

**Comment by Rod-Serling** [comment]
A rudimentary Windows WIX installer has been added. It doesn't check .NET requirements, and is very basic. I kinda did it before I realized WIX was windows only. If we want to delete it for something multiplatform I have no issue. I don't plan on updating it until we release Alpha 4 at the earliest.

**Comment by agm-114** [comment]
Added to Ideas
