### ISSUE TITLE
ECS: Facility code Re-Write

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#86]
The current implementation of facility code needs to be re-written to match how components are done.
a facility and a component should be fairly similar entities. 

Edit: 
Mines are sorta done.
hard bits are: 
Figuring out how employment should be done (it should check the component required crew for the number of pop required to run) 

Figuring out how Research should be handled.

Figuring out how jobs should be handled, I've got some ideas on this... probibly we have a job/task/somethin SD which should define input (minerals, component parts etc) and outputs (refined stuff ie fuel, ship component objects/facilities) 
a new DataBlob which holds a list/dictionary of these jobs/tasks/somethings SDs and also sets whether they are automatic/repeating job (ie sorium to fuel refining) or a set number ie for fighters/shipcomponents/facilities (user should be able to set this, but also should be a default setting somewhere, (in the jobSD or in the jobDB and set in the componentDesignSD?)  

Figuring out how we're going to enable and disable facilities, set jobs etc. this will likely be related to ordering ships themselves around too. 

Easier stuff is just adding the different ability DataBlobs and processors.

**Comment by se5a** [comment]
you know what?
we could probably treat facilities exactly the same as components now with regards to this.
Maybe just add an abilityDB for whether the 'component' can be placed on a planet, Ship, PDC etcetc.
Processors still need to be written however.

**Comment by iceball3** [comment]
Is anyone currently working on this specifically? I've finally begun to get into C# (Have some java classes behind me but I've rusted), and while what I know is tremendous, I'm thinking of choosing a starting point and seeing if I can still figure out problems well enough. That said, if someone is already working on this, I don't want to bar you from working on it as you'll probably do it better anyway.
Apologies if I'm not very much used to the formalities of developing and interacting on github, this is the first project I'm thinking of contributing to.

**Comment by se5a** [comment]
Unless you're familiar with ECS style code,  this might be a little hard to
start with. Don't let that stop you taking a look and trying to figure it
out though.  I've started doing a little in the ecs ship components
branch,  the code for mines is mostly there. If you want something a bit
easier to mess with over the weekend,  maybe take a look at the wpf ui
stuff.  See if you can get the system info page a bit prettier, or see if
you can see why the orbit lines look wrong in the system map... I'm away
till sunday, but when I get back you should be able to catch me on IRC for
questions.

**Comment by se5a** [comment]
I guess I scared you away...

**Comment by iceball3** [comment]
Bah, sorry! I had a lot more than i hoped for occurring in the past and next few days that has made going forward with my life rather daunting, to say the least. I figure now I need to learn a lot more before I'm ready to start contributing, so that I can understand what I am even touching (that and I need to learn more before I can consider employment in programming to begin with). I apologize if my bad communication muddled things up. What is the IRC again? I am not sure where to find the information on it.

**Comment by se5a** [comment]
Haha no worries, it's probably not a bad project to start helping with as stuff is fairly loosely coupled, meaning you can screw up one part of it and not have it affect other bits too much, as far as individual components/facilities go anyway. 
Catch me on IRC and we'll see if we can set you up with something not too daunting and get you a feel for it.
If you've not already, install visual studio 2013 (or 2015 should work fine too) comunity edition. 
Then fork the ECS Ship Components branch in github (that way you can make pull requests which I can take a look at and then accept) 
IRC is #pulsar4x on freenode

**Comment by se5a** [comment]
So I think the hard code behind this is mostly done, from here its just writing up the ability datablobs and processors, then the json code for the facility designs (facilities are now handled in pulsar almost exactly the same way as ship subsystems, ie they can be designed if so required)
