### ISSUE TITLE
ECS DataBob Tests should make sense and be clear.

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#88]
Because seriously, WTF does "will deserialize with the default parameterless constructor" and all the rest of them mean. create a wiki page and link to it or something.

**Comment by Rod-Serling** [comment]
It's a test to make sure JSON can properly create each datablob. Datablobs need to have constructors that can be used by JSON to create the objects, and those are the four options. Additionally, the way they're listen is the priority JSON will take when trying to find an object type's constructor.

`    public class NewDataBlob1 : BaseDataBlob
    {
        [JsonConstructor]
        public NewDataBlob1()
        {
            // This is the constructor marked with [JsonConstructor] 
        }
    }

    public class NewDataBlob2 : BaseDataBlob
    {
        public NewDataBlob2(/*parameterless*/)
        {
            // This is the default parameterless constructor
        }
    }

    public class NewDataBlob3 : BaseDataBlob
    {
        [JsonProperty("PropertyName")]
        public string Property1;

        public NewDataBlob3(string PropertyName) // <- 1 Parameter here. Can have more than 1.
        {
            // This is the only parametrized constructor available.
            // JSON serializer will populate the PropertyName var
            Property1 = PropertyName;
        }
        // NOTE: you can ONLY have ONE parameterized constructor to be able to use this, otherwise JSON wont know which one to use.
    }

    public class NewDataBlob4 : BaseDataBlob
    {
        private NewDataBlob4()
        {
            // This is the private default parameterless constructor. 
            // JSON will brute-force its way into your private class and use the private construtor as a last resort.
        }
    }
`

**Comment by se5a** [comment]
When it fails, it needs to give a clear and concise message as to what the data-blob author is missing.

**Comment by Rod-Serling** [comment]
Assert.Fail(dataBlobType.ToString() + " does not have a Json constructor");

Prints out "NewDataBlob does not have a Json constructor"

Is that not clear?
"NewDataBlob does not have a constructor JSON can use" ? is that better?

**Comment by se5a** [comment]
Is that the only test? Also think about it from a new coders pov.  He
doesn't know what a json constructor is.
Also i think originally this issue was created after attempting to run
tests in debug,  which will halt/pause on passing tests if the test is
looking for an exception.  This is also extremely confusing,  though i
don't know if its possible to fix that.

**Comment by Rod-Serling** [comment]
Issue resolved as of commit a0b32972b9b4c093135611c1946f0bb82e088695
