### ISSUE TITLE
upgrade Nunit 3.0 (when stable release)

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#94]
Currently Nunit 3.0 is in candidate release. 

This should be a fairly easy switchover: 

http://nunit.org/index.php?p=upgrade&r=3.0

http://nunit.org/index.php?p=breakingChanges&r=3.0

**Comment by firefly2442** [comment]
Dead links:

https://github.com/nunit/nunit/wiki/Upgrading

https://github.com/nunit/nunit/wiki/Breaking-Changes

**Comment by firefly2442** [comment]
Well, I attempted to fix this but I'm getting some error about "skipped loaded assembly because it references an unsupported version of the nunit.framework".  Maybe it's some error upstream in Monodevelop?  Ugh, I'm not sure...

**Comment by se5a** [comment]
so this is done now yes? shall I close it?

**Comment by firefly2442** [comment]
I believe so from this commit: f00050ba7f6025045ae0ae38ad700a079e3106f9

If someone could perhaps just run the tests and check those that would be great.  I'm getting an internal error in Monodevelop for nunit for some reason and I can't run them.

**Comment by se5a** [comment]
Yes the tests are passing. I'll close this.
